let base_url = "https://coralecom-react.cloud6.ae/";

export const redirectMap = {
  "/products/category/perfumes": `${base_url}/product-category/perfumes/`,
  "/products/category/perfume-oil": `${base_url}/product-category/perfume-oils/`,
  "/products/category/watches": `${base_url}/product-category/watches/`,
  "/products/category/mens-perfumes": `${base_url}/product-category/men-perfumes/`,
  "/products/category/women-perfumes": `${base_url}/product-category/women-perfume/`,
  "/products/category/gift-set": `${base_url}/product-category/gift-set/`,
  "/products/category/unisex-perfumes": `${base_url}/product-category/unisex-perfumes/`,
  "/products/category/exclusive-brands": `${base_url}/product-category/exclusive-brands/`,
  "/products/category/accessories": `${base_url}/product-category/accessories/`,
  "/products/category/arabic-perfume": `${base_url}/product-category/arabic-perfumes/`,
  "/products/category/niche-perfumes": `${base_url}/product-category/niche-perfumes/`,
  "/products/category/inspired-perfume": `${base_url}/product-category/creations/`,
  "/products/category/body-mist": `${base_url}/product-category/body-mists/`,
  "/products/category/essential-oils": `${base_url}/product-category/creations/essential-oil`,
  "/products/category/musk-collections": `${base_url}/product-category/musk-collections/`,
  "/products/category/watches-for-men": `${base_url}/product-category/watches/`,
  "/products/category/sanitizer": `${base_url}/product-category/hand-sanitizers/`,
  "/products/category/deodorant": `${base_url}/product-category/deodorant/`,
  "/products/category/diffuser": `${base_url}/product-category/diffusers/`,
  "/products/category/best-seller": `${base_url}/product-category/best-seller/`,
  "/products/category/concentrated-perfume-oil": `${base_url}/product-category/perfume-oils/`,
};
